import { Folder } from './drive.ts';

export const devData: { [key: string]: Folder } = {
    '0': {
        name: "My Drive",
        fileId: "root",
        size: 0,
        subfolders: [],
    },

    '1': {
        name: "My Drive",
        fileId: "root",
        size: 10,
        subfolders: [
            {
                name: "folder 1",
                fileId: "1",
                size: 15,
                subfolders: [],
            },
            {
                name: "folder 2",
                fileId: "2",
                size: 13,
                subfolders: [
                    {
                        name: "folder 2a",
                        fileId: "2a",
                        size: 50,
                        subfolders: [],
                    },
                ],
            },
            {
                name: "folder 3",
                fileId: "3",
                size: 13,
                subfolders: [],
            },
        ],
    },

    '2': {
        name: "My Drive",
        fileId: "root",
        size: 10,
        subfolders: [
            {
                name: "folder 1",
                fileId: "1",
                size: 15,
                subfolders: [],
            },
            {
                name: "folder 2",
                fileId: "2",
                size: 13,
                subfolders: [
                    {
                        name: "folder 2a",
                        fileId: "2a",
                        size: 50,
                        subfolders: [
                            {
                                name: "folder 2a1",
                                fileId: "2a1",
                                size: 15,
                                subfolders: [],
                            },
                            {
                                name: "folder 2a2",
                                fileId: "2a2",
                                size: 13,
                                subfolders: [
                                    {
                                        name: "folder 2a2a",
                                        fileId: "2a2a",
                                        size: 5,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2b",
                                        fileId: "2a2b",
                                        size: 2,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2c",
                                        fileId: "2a2c",
                                        size: 2,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2d",
                                        fileId: "2a2d",
                                        size: 5,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2e",
                                        fileId: "2a2e",
                                        size: 3,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2f",
                                        fileId: "2a2f",
                                        size: 5,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2g",
                                        fileId: "2a2g",
                                        size: 1,
                                        subfolders: [],
                                    },
                                ],
                            },
                            {
                                name: "folder 2a3",
                                fileId: "2a3",
                                size: 13,
                                subfolders: [],
                            },
                        ],
                    },
                ],
            },
            {
                name: "folder 3",
                fileId: "3",
                size: 13,
                subfolders: [
                    {
                        name: "folder 3a",
                        fileId: "3a",
                        size: 1,
                        subfolders: [
                            {
                                name: "folder 3a1",
                                fileId: "3a1",
                                size: 0,
                                subfolders: [
                                    {
                                        name: "folder 3a1a",
                                        fileId: "3a1a",
                                        size: 1,
                                        subfolders: [
                                            {
                                                name: "folder 3a1a1",
                                                fileId: "3a1a1",
                                                size: 7,
                                                subfolders: [],
                                            },
                                        ],
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },

    '3': {
        name: "My Drive",
        fileId: "root",
        size: 10,
        subfolders: [
            {
                name: "folder 1",
                fileId: "1",
                size: 15,
                subfolders: [
                    { name: "folder 1a", fileId: "folder 1a", size: 3, subfolders: [] },
                    { name: "folder 1b", fileId: "folder 1b", size: 3, subfolders: [] },
                    { name: "folder 1c", fileId: "folder 1c", size: 3, subfolders: [] },
                    { name: "folder 1d", fileId: "folder 1d", size: 3, subfolders: [] },
                    { name: "folder 1e", fileId: "folder 1e", size: 3, subfolders: [] },
                    { name: "folder 1f", fileId: "folder 1f", size: 3, subfolders: [] },
                    { name: "folder 1g", fileId: "folder 1g", size: 3, subfolders: [] },
                    { name: "folder 1h", fileId: "folder 1h", size: 3, subfolders: [] },
                    { name: "folder 1i", fileId: "folder 1i", size: 3, subfolders: [] },
                    { name: "folder 1j", fileId: "folder 1j", size: 3, subfolders: [] },
                    { name: "folder 1k", fileId: "folder 1k", size: 3, subfolders: [] },
                    { name: "folder 1l", fileId: "folder 1l", size: 3, subfolders: [] },
                    {
                        name: "folder 1m",
                        fileId: "1m",
                        size: 0,
                        subfolders: [
                            { name: "folder 1m1", fileId: "1m1", size: 1, subfolders: [] },
                            { name: "folder 1m2", fileId: "1m2", size: 1, subfolders: [] },
                            { name: "folder 1m3", fileId: "1m3", size: 1, subfolders: [] },
                            { name: "folder 1m4", fileId: "1m4", size: 1, subfolders: [] },
                            { name: "folder 1m5", fileId: "1m5", size: 5, subfolders: [] },
                            { name: "folder 1m6", fileId: "1m6", size: 1, subfolders: [] },
                            { name: "folder 1m7", fileId: "1m7", size: 1, subfolders: [] },
                            { name: "folder 1m8", fileId: "1m8", size: 1, subfolders: [] },
                            { name: "folder 1m9", fileId: "1m9", size: 1, subfolders: [] },
                            { name: "folder 1m10", fileId: "1m10", size: 1, subfolders: [] },
                            { name: "folder 1m11", fileId: "1m11", size: 1, subfolders: [] },
                            { name: "folder 1m12", fileId: "1m12", size: 1, subfolders: [] },
                            { name: "folder 1m13", fileId: "1m13", size: 1, subfolders: [] },
                            { name: "folder 1m14", fileId: "1m14", size: 1, subfolders: [] },
                            { name: "folder 1m15", fileId: "1m15", size: 1, subfolders: [] },
                            { name: "folder 1m16", fileId: "1m16", size: 1, subfolders: [] },
                            { name: "folder 1m17", fileId: "1m17", size: 1, subfolders: [] },
                            { name: "folder 1m18", fileId: "1m18", size: 1, subfolders: [] },
                            { name: "folder 1m19", fileId: "1m19", size: 1, subfolders: [] },
                            { name: "folder 1m20", fileId: "1m20", size: 1, subfolders: [] },
                            { name: "folder 1m21", fileId: "1m21", size: 1, subfolders: [] },
                            { name: "folder 1m22", fileId: "1m22", size: 1, subfolders: [] },
                            { name: "folder 1m23", fileId: "1m23", size: 1, subfolders: [] },
                            { name: "folder 1m24", fileId: "1m24", size: 1, subfolders: [] },
                            { name: "folder 1m25", fileId: "1m25", size: 1, subfolders: [] },
                            { name: "folder 1m26", fileId: "1m26", size: 1, subfolders: [] },
                            { name: "folder 1m27", fileId: "1m27", size: 1, subfolders: [] },
                            { name: "folder 1m28", fileId: "1m28", size: 1, subfolders: [] },
                            { name: "folder 1m29", fileId: "1m29", size: 1, subfolders: [] },
                            { name: "folder 1m30", fileId: "1m30", size: 1, subfolders: [] },
                            { name: "folder 1m31", fileId: "1m31", size: 1, subfolders: [] },
                            { name: "folder 1m32", fileId: "1m32", size: 1, subfolders: [] },
                            { name: "folder 1m33", fileId: "1m33", size: 1, subfolders: [] },
                            { name: "folder 1m34", fileId: "1m34", size: 1, subfolders: [] },
                            { name: "folder 1m35", fileId: "1m35", size: 1, subfolders: [] },
                            { name: "folder 1m36", fileId: "1m36", size: 1, subfolders: [] },
                            { name: "folder 1m37", fileId: "1m37", size: 1, subfolders: [] },
                            { name: "folder 1m38", fileId: "1m38", size: 1, subfolders: [] },
                            { name: "folder 1m39", fileId: "1m39", size: 1, subfolders: [] },
                            { name: "folder 1m40", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m41", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m42", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m43", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m44", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m45", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m46", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m47", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m48", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m49", fileId: "1m", size: 1, subfolders: [] },
                            { name: "folder 1m50", fileId: "1m", size: 1, subfolders: [] },
                        ]
                    },
                    { name: "folder 1n", fileId: "folder 1n", size: 3, subfolders: [] },
                    { name: "folder 1o", fileId: "folder 1o", size: 3, subfolders: [] },
                    { name: "folder 1p", fileId: "folder 1p", size: 3, subfolders: [] },
                    { name: "folder 1q", fileId: "folder 1q", size: 3, subfolders: [] },
                    { name: "folder 1r", fileId: "folder 1r", size: 3, subfolders: [] },
                    { name: "folder 1s", fileId: "folder 1s", size: 3, subfolders: [] },
                    { name: "folder 1t", fileId: "folder 1t", size: 3, subfolders: [] },
                    { name: "folder 1u", fileId: "folder 1u", size: 3, subfolders: [] },
                    { name: "folder 1v", fileId: "folder 1v", size: 3, subfolders: [] },
                    { name: "folder 1w", fileId: "folder 1w", size: 3, subfolders: [] },
                    { name: "folder 1x", fileId: "folder 1x", size: 3, subfolders: [] },
                    { name: "folder 1y", fileId: "folder 1y", size: 3, subfolders: [] },
                    { name: "folder 1z", fileId: "folder 1z", size: 3, subfolders: [] },
                ],
            },
            {
                name: "folder 2",
                fileId: "2",
                size: 13,
                subfolders: [
                    {
                        name: "folder 2a",
                        fileId: "2a",
                        size: 50,
                        subfolders: [
                            {
                                name: "folder 2a1",
                                fileId: "2a1",
                                size: 15,
                                subfolders: [],
                            },
                            {
                                name: "folder 2a2",
                                fileId: "2a2",
                                size: 13,
                                subfolders: [
                                    {
                                        name: "folder 2a2a",
                                        fileId: "2a2a",
                                        size: 5,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2b",
                                        fileId: "2a2b",
                                        size: 2,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2c",
                                        fileId: "2a2c",
                                        size: 2,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2d",
                                        fileId: "2a2d",
                                        size: 5,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2e",
                                        fileId: "2a2e",
                                        size: 3,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2f",
                                        fileId: "2a2f",
                                        size: 5,
                                        subfolders: [],
                                    },
                                    {
                                        name: "folder 2a2g",
                                        fileId: "2a2g",
                                        size: 1,
                                        subfolders: [],
                                    },
                                ],
                            },
                            {
                                name: "folder 2a3",
                                fileId: "2a3",
                                size: 13,
                                subfolders: [],
                            },
                        ],
                    },
                ],
            },
            {
                name: "folder 3",
                fileId: "3",
                size: 13,
                subfolders: [
                    {
                        name: "folder 3a",
                        fileId: "3a",
                        size: 1,
                        subfolders: [
                            {
                                name: "folder 3a1",
                                fileId: "3a1",
                                size: 0,
                                subfolders: [
                                    {
                                        name: "folder 3a1a",
                                        fileId: "3a1a",
                                        size: 1,
                                        subfolders: [
                                            {
                                                name: "folder 3a1a1",
                                                fileId: "3a1a1",
                                                size: 7,
                                                subfolders: [],
                                            },
                                        ],
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },
}
